### PR TITLE
Fixed issue with multiple instances conflicting

### PR DESCRIPTION
**Pull request by mrkmg**
Added "extension: '.pug'" to default options (seeing as this is intended for pug)
Updated tests to use pug files

### CODE REVIEW

**Comment by mrkmg** [comment]
This is a fix for the issue mentioned here: https://github.com/mrkmg/laravel-elixir-pug/issues/11

Basically, if you have multiple tasks which use gulp-pug-inheritance, files will end up all mix-matched between to instances. It was solved by moving the var stream and var errors into the main function (new instance of the variable for each call to the plugin).

**Comment by pure180** [comment]
Thanks for your maintenance. But i guess we don't need to adjust the file extension options here in this Plugin. It would be better to adjust this directly in [pug-inheritance](https://github.com/adammockor/pug-inheritance) and then update the dependencies of this plugin to the current version of pug-inheritance. Because it allready got a default file extension, but for now its still set to `*.jade`, i got write access and i'll change it later and ask @adammockor to release it soon.
But I can merge and publish your changes temporarily if needed?

**Comment by mrkmg** [comment]
I can update this commit to not include the change to the default extension. I just assumed that since there are two separate packages (gulp-jade-inheritanace, and gulp-pug-inheritance), I would make this one default to .pug. Really, the only change needed to fix the issue is moving var stream from outside the main function to inside it.

Would it be better to make a new PR with only that change?

**Comment by pure180** [comment]
Ah okay... now I understand. Sorry didn't read the mentioned issue sufficiently.
Please just update your commit and execlude the default extension. I'll merge and publish it then soon when I'm at home after work. :-)

**Comment by mrkmg** [comment]
I have removed the default extension, and added the extension option to each test.

**Comment by adammockor** [comment]
So should we switch to pug as default? https://github.com/adammockor/pug-inheritance/issues/9

**Comment by pure180** [comment]
Good morning @adammockor, yes this would be great. Can you publish it then soon?
@mrkmg The changes are published on NPM.

**Pull request merged**
